services:
  tanipintar-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanipintar-bot
    restart: unless-stopped
    depends_on:
      - waha
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - WAHA_BASE_URL=http://waha:3000
    volumes:
      - ./logs:/app/logs
    networks:
      - tanipintar-network

  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: unless-stopped
    shm_size: '1gb'
    ports:
      - "3000:3000"
    environment:
      - WAHA_DASHBOARD_ENABLED=true
      - WAHA_DASHBOARD_NO_PASSWORD=True
      - WAHA_DASHBOARD_PASSWORD=
      - WAHA_NO_API_KEY=True
      - WAHA_API_KEY=
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_FILES_LIFETIME=3600
      - WHATSAPP_HOOK_URL=http://tanipintar-bot:8000/webhook/waha
      - WHATSAPP_HOOK_EVENTS=message
    volumes:
      - ./waha_data:/app/.sessions
    networks:
      - tanipintar-network

networks:
  tanipintar-network:
    driver: bridge
